name: Deploy to Prod
on:
  pull_request:
    types:
      - closed
    branches:
      - 'master'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ HOST }}
        username: ${{ USERNAME }}
        key: ${{ SSH_KEY }}
        script: whoami
